server:
  port: 0

spring:
  sql:
    init:
      mode: always
      platform: postgresql
      schema-locations: classpath:schema.sql

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6543/ewm
    username: main
    password: main

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect

discovery:
  services:
    stats-server-id: stats-server

logging:
  level:
    ru.practicum: DEBUG