services:
  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ewm_stats
      POSTGRES_USER: stats
      POSTGRES_PASSWORD: stats
    ports:
      - "6542:5432"

  ewm-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
    ports:
      - "6543:5432"

  users-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ewm_users
      POSTGRES_USER: users
      POSTGRES_PASSWORD: users
    ports:
      - "6544:5432"

  requests-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ewm_requests
      POSTGRES_USER: requests
      POSTGRES_PASSWORD: requests
    ports:
      - "6545:5432"