CREATE TABLE IF NOT EXISTS participation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created TIMESTAMP NOT NULL,
    event_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    status VARCHAR(15)
    CHECK (status IN ('confirmed', 'rejected', 'pending')) NOT NULL,
    CONSTRAINT pk_participation_requests PRIMARY KEY (id)
    );