syntax = "proto3";

package stats.service.dashboard;

import "stats/messages/user_predictions_request.proto";
import "stats/messages/recommended_event.proto";
import "stats/messages/similar_events_request.proto";
import "stats/messages/interaction_count_request.proto";

option java_package = "ru.practicum.ewm.stats.proto";

service RecommendationController {
  rpc GetRecommendationForUser (stats.message.UserPredictionsRequestProto)
      returns (stats.message.RecommendedEventProto);

  rpc GetSimilarEvents (stats.message.SimilarEventsRequestProto)
      returns (stats.message.RecommendedEventProto);

  rpc GetInteractionsCount (stats.message.InteractionCountRequestProto)
      returns (stats.message.RecommendedEventProto);
}