spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**

        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        cloud:
          gateway=DEBUG:
  reactor:
    netty:
      http:
        server=DEBUG: