server:
  port: 0

spring:
  sql:
    init:
      mode: always
      platform: postgresql
      schema-locations: classpath:schema.sql

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6543/ewm_event
    username: event
    password: event

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect

discovery:
  services:
    stats-server-id: stats-server

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 50
      failureRateThreshold: 50
  instances:
    event-service:
      slidingWindowSize: 10
      waitDurationInOpenState: 10000
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true

grpc:
  client:
    analyzer:
      address: 'discovery:///analyzer'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    ru.practicum: DEBUG